### ISSUE TITLE
Some trips have all values set to N/A

### ISSUE THREAD

**Issue by shankari** [asiripanich/emdash#15]
After #13 by @ahcyip, I now see some trips in the map view which have N/A for all values except the user_id. For example, the trips from the Bay Area to Hawaii (see screenshot below).

<img width="627" alt="Screen Shot 2020-11-10 at 8 48 23 PM" src="https://user-images.githubusercontent.com/2423263/98770014-1dfb3100-2396-11eb-9901-b89957c4852e.png">

<img width="627" alt="Screen Shot 2020-11-10 at 8 40 32 PM" src="https://user-images.githubusercontent.com/2423263/98769587-15562b00-2395-11eb-94c9-4c9930b02886.png">

That seems wrong. If we look at the trip table for example, there are no entries with N/A

For example, the trip from the Bay Area to Hawaii is row 9 since the start timezone is PDT and the end timezone is HST. 
The trip from the Bay Area to Hawaii doesn't show up here because I had my phone off, but is hidden between 38 and 39.

And entries 9, 38 and 39 all have all entries present, including duration, distance and start and end times. Why does this show up as N/A in the map?

**Comment by shankari** [comment]
Investigating this further, the trip from the Bay Area to Hawaii is actually two lines. One of them is for row 9 and has all the information filled out. The other is for row 51 and has all N/A values

<img width="627" alt="Screen Shot 2020-11-11 at 8 15 24 AM" src="https://user-images.githubusercontent.com/2423263/98836302-621e1e00-23f6-11eb-8894-8331d68a8228.png">
<img width="507" alt="Screen Shot 2020-11-11 at 8 15 39 AM" src="https://user-images.githubusercontent.com/2423263/98836312-65b1a500-23f6-11eb-9df5-15937af86ae2.png">

But if I look at the trip table, there are only 50 trips for user 192c82d3c1da4a679edaceb81693fce1. Row 51 is for user d38b6b9e442a4b5baaabf7bf39018895.

@ahcyip any thoughts on how this spurious trip is created in the map version alone? Maybe there is a bad join with the location table that is inserting blank entries?

**Comment by ahcyip** [comment]
Yes, sounds like a bad join. `foverlaps` says it fills in everything with NAs if there's no match. The code for the join is:
```{r}
  # drop trip geometries (just a line between OD) and set trips as data.table
  tidied_trips <- tidied_trips %>% sf::st_drop_geometry()
  data.table::setDT(tidied_trips)
  # set locations as data.table and duplicate location time to set an "interval"
  data.table::setDT(tidied_locations)[, fmt_time_utc_end := fmt_time_utc] 
  # join locations to trips according to time interval overlap (all done in UTC time for consistency)
  data.table::setkey(tidied_locations, user_id, fmt_time_utc, fmt_time_utc_end)
  data.table::setkey(tidied_trips, user_id, start_fmt_time, end_fmt_time)
  joined_trips_and_locs <- data.table::foverlaps(tidied_locations, tidied_trips)
```
Sorry, I don't have time before Friday to look into this

**Comment by shankari** [comment]
I wonder if a hack is as simple as `drop_na` or the equivalent for R. Is the fmt_time in string format or datetime? If it is a string, we should use the `start_ts` and `end_ts` instead which are already UTC numbers.

Wrestling with R always takes more time than I expect because the syntax is deceptively similar but not identical to pandas dataframes. I might just wait until Friday and let you fix this.

**Comment by ahcyip** [comment]
the fmt_time is in datetime.
yes, the NAs can be dropped. If you know the NAs are spurious, just add nomatch=NULL
`data.table::foverlaps(tidied_locations, tidied_trips, nomatch=NULL)`

**Comment by asiripanich** [comment]
Please see my https://github.com/asiripanich/emdash/pull/14#issuecomment-726434987 here.

**Comment by asiripanich** [comment]
Closing this issue with PR #14.
