### ISSUE TITLE
The interactive plot screen doesn't work

### ISSUE THREAD

**Issue by asiripanich** [asiripanich/emdash#22]
@asiripanich I have another question for the table/interactive plot screen,
the table displayed at the page bottom seems fine, however I don't understand how to display a graph, I tried for instance simply to put user_ID in X and n_Trips in Y but nothing is displayed (even if I click on "play").

_Originally posted by @PatGendre in https://github.com/asiripanich/emdash/issues/20#issuecomment-744247949_

**Comment by asiripanich** [comment]
@PatGendre using your trip table, can you make this graph? the duration column in x and the distance column in y.

![image](https://user-images.githubusercontent.com/17020181/102758922-8d1d6980-43c7-11eb-89d0-f7e7505381c6.png)

**Comment by PatGendre** [comment]
@asiripanich actually I have no duration and distance variable, this may be an hint my database is not correct?

![sshotemdash](https://user-images.githubusercontent.com/5039447/102768665-cf23bc80-4381-11eb-944a-0abddeef2982.png)

**Comment by asiripanich** [comment]
The fields that you see in the plot panel is actually linked with the table below. So if you select the 'Trips' table instead of the 'Participants' table you should have the distance and duration fields.

Btw, I'm not sure what the play button is for but you shouldn't need it.

**Comment by PatGendre** [comment]
Thanks @asiripanich, the graph is displayed ! Sorry I didn't see this :-(
I suppose you can close the issue :-)

**Comment by shankari** [comment]
catching up on my pending tasks...
I also see that the trips plot works just fine.

@PatGendre One additional note that I figured out was that the graph is linked to the table, but the filters for the table and graph are different. For the table, you can filter using the fields on the top row. But IIRC, that filter doesn't apply to the graph. To modify the graph, you need to change the filters in the "Data" button right below the plot.

@asiripanich am I right?

**Comment by asiripanich** [comment]
> catching up on my pending tasks...
> I also see that the trips plot works just fine.
> 
> @PatGendre One additional note that I figured out was that the graph is linked to the table, but the filters for the table and graph are different. For the table, you can filter using the fields on the top row. But IIRC, that filter doesn't apply to the graph. To modify the graph, you need to change the filters in the "Data" button right below the plot.
> 
> @asiripanich am I right?

@shankari that's correct! ;)
