### ISSUE TITLE
Editing and debugging the dashboard in RStudio

### ISSUE THREAD

**Issue by allenmichael099** [asiripanich/emdash#25]
Is there a way to make changes to the dashboard in RStudio without having to reinstall the package each time a change is made? I cloned emdash on my computer, and each time I want to test out my new changes, I use something like this:

detach("package:emdash", unload = TRUE)
remotes::install_local(path = 'C:/Users/mallen2/emdash',upgrade="never",force = TRUE)
library(emdash)
emdash::run_app(mongo_url = 'mongodb://localhost:27017')

**Comment by asiripanich** [comment]
hi @allenmichael099, try ‘devtools::load_all()’.

https://www.r-project.org/nosvn/pandoc/devtools.html

**Comment by asiripanich** [comment]
No need to do ‘library(emdash)’ after.

**Comment by asiripanich** [comment]
For debugging see https://shiny.rstudio.com/articles/debugging.html.
