### ISSUE TITLE
CI is red; not sure if this works on linux?

### ISSUE THREAD

**Issue by shankari** [asiripanich/emdash#3]
@asiripanich I took a look at the CI output since I want to start with a working version and make sure that I don't break anything.

It looks like windows and OSX pass, but linux fails because 

```
* checking package dependencies ... ERROR
Error: Packages required but not available:
  'mapview', 'mongolite', 'randomcoloR', 'sf'
```

I took a look at the `mapview` package, and it looks like it has binaries only for windows and OSX
https://cloud.r-project.org/web/packages/mapview/index.html

```
Windows binaries: | r-devel: mapview_2.9.0.zip, r-release: mapview_2.9.0.zip, r-oldrel: mapview_2.9.0.zip
macOS binaries: | r-release: mapview_2.9.0.tgz, r-oldrel: mapview_2.9.0.tgz
```

Could that be the reason why?

**Comment by asiripanich** [comment]
Umm I'm not entirely sure. I will try to fix this on the `fix-gha-ci` branch. However, I didn't have any problem when I installed the package inside an ubuntu docker container.
