### ISSUE TITLE
Restore the user_name to the participant table

### ISSUE THREAD

**Issue by shankari** [asiripanich/emdash#36]
The program managers plan to use the dashboard to view travel patterns. But if they need to follow up with individual people, they need to know who they are, and the UUID doesn't give that information. Displaying the "user_name" (a random token in our case) allows them to make that linkage.

This should be displayed at least in the participant table, but may be added to the trip table as well for greater ease of use.

**Comment by shankari** [comment]
@allenmichael099 Is this as simple as removing this?
https://github.com/asiripanich/emdash/blob/3cf120124f61ad3d0566940cce31c35c1afe7916/R/utils_tidy_data.R#L26

**Comment by allenmichael099** [comment]
@shankari You're right, removing that leads the dashboard to display user_email in the participant table.

**Comment by shankari** [comment]
Great! Can you submit the PR for it? If @asiripanich can merge it, I can update the dashboard for two real deployers today!

**Comment by asiripanich** [comment]
We should add this as an option in the config file. #32
