### ISSUE TITLE
Regression: Plot is not synced with table (even for trips)

### ISSUE THREAD

**Issue by shankari** [asiripanich/emdash#55]
Found today while demoing the dashboard to program administrators, see screenshots:

| Participant tab, participant labels on top | Trip tab, also participant labels on top | 
|------|------|
| <img width="646" alt="Screen Shot 2021-07-23 at 5 50 02 PM" src="https://user-images.githubusercontent.com/2423263/126852810-8da83405-1903-4c53-b60c-a17a5a2fc5ec.png"> |<img width="646" alt="Screen Shot 2021-07-23 at 5 50 12 PM" src="https://user-images.githubusercontent.com/2423263/126852808-706f4bd1-a2f9-4614-8db1-c4bc5e7dcb8a.png"> |

**Comment by shankari** [comment]
When we fix this, maybe we can have the plot sync with the other tables as well

**Comment by asiripanich** [comment]
Fixing this.
