### ISSUE TITLE
Bug (existing?): the colors on the map don't seem to match up as we modify the filters

### ISSUE THREAD

**Issue by shankari** [asiripanich/emdash#56]
We thought this was related to my change to map the mode to the z-axis, but @allenmichael099 said that it happens even when the user_id is mapped to the z-axis (as on master).

It is very confusing because you think that the colors are right, but they are wrong.

@asiripanich since you originally implemented the map, maybe you can give us some pointers?

**Comment by asiripanich** [comment]
I cannot reproduce it using the test database. Could share me some screenshots? Thanks.

**Comment by allenmichael099** [comment]
@asiripanich Using the test database, the two user paths are consistently labeled with the correct user_ids. With more users, the colors are incorrect.
User 1fdb... is green in the legend (second row), but purple on the map. To reproduce the issue with the test database, you can change the mapview zcol to 'mode_confirm', where the legend colors are consistently wrong. Pull request #62 makes the zcol configurable, if you would like to easily change between user_id and mode_confirm.

![image](https://user-images.githubusercontent.com/56986329/128084862-3753727f-7852-485a-9d3e-ea5e54e24479.png)
