### ISSUE TITLE
Map sometimes does not update

### ISSUE THREAD

**Issue by allenmichael099** [asiripanich/emdash#61]
When I use emdash-test-db data with `load_trips_start_ndays` set to 7, 
then within emdash select 2015-07-22 or 2015-07-23 as the first date, 
then click 'Load trips data', the trip lines do not display. 

Trip lines do display in these cases:

- after clicking 'Load trips data' a second time.
- after 'continuing' when I place a `browser()` statement in `app_server` within `observeEvent(filtered_trips()$data_filtered(), {` before `callModule`

**Comment by asiripanich** [comment]
We tried to reproduce this in our meeting but couldn't. Let's close this issue for now until we have a reproducible step to test this.
