### ISSUE TITLE
Serialize JSON in the trips table

### ISSUE THREAD

**Issue by shankari** [asiripanich/emdash#69]
As part of the auto-labeling functionality, we added the set of automatically inferred labels to each confirmed trip object. These labels are a JSON dict `[{labels: {mode_confirm: X, replace_confirm: Y}, p: <probability>}]`, similar to 

```
[{'labels': {'mode_confirm': 'bike',
   'purpose_confirm': 'exercise',
   'replaced_mode': 'shared_ride'},
  'p': 0.5},
 {'labels': {'mode_confirm': 'bike',
   'purpose_confirm': 'home',
   'replaced_mode': 'shared_ride'},
  'p': 0.5}]
```

These show up automatically in the data table, but because this is a JSON array, they show up as `[(object Object), (object Object)]` (see screenshot). Would it be possible to `JSON.serialize` this field so the deployer can get a sense of what the trip might be even if the user hasn't labeled it? I think @allenmichael099 had an example of applying a javascript transform to a column (for the bike checkinout table).

<img width="476" alt="image001" src="https://user-images.githubusercontent.com/2423263/130156392-48931d10-5b8a-485b-88b1-f8f2ce784be6.png">

**Comment by asiripanich** [comment]
Sure, I can test this once the feature is on the main branch.

**Comment by shankari** [comment]
The feature is in main now
https://github.com/e-mission/e-mission-server/pull/829

There is a new release
https://github.com/e-mission/e-mission-server/releases/tag/v3.0.0

a new basic docker image
https://hub.docker.com/repository/docker/emission/e-mission-server

I still haven't updated the crontab
https://github.com/e-mission/e-mission-docker/blob/master/examples/em-server-multi-tier-cronjob/analysis/crontab
with the new job (sorry, stuck on my work laptop) but should be able to update it early next week.
